- name: Ansible Variable
  hosts: web
  vars: #play level vars
    Name: "Charan"
    Amount: 15,000
    Sender: "Abc"
    Bank: "XYZ"
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: "Hello {{Name}}, you've received INR {{Amount}} in your account. Woohoo! it was sent by {{Sender}} on Dec 24,2024 -{{Bank}}"
  
  - name: Print message
    vars: # task level vars
      Amount: 20,000
    ansible.builtin.debug:
      msg: "Hello {{Name}}, you've received INR {{Amount}} in your account. Woohoo! it was sent by {{Sender}} on Dec 24,2024 -{{Bank}}"
  
  - name: Print message
    ansible.builtin.debug:
      msg: "Hello {{Name}}, you've received INR {{Amount}} in your account. Woohoo! it was sent by {{Sender}} on Dec 24,2024 -{{Bank}}"
            