- name: variables from file
  hosts: web
  vars_files:
  - vars.yml
  tasks: 
  - name: print msg
    ansible.builtin.debug:
      msg: "Hello {{Name}}, you've received INR {{Amount}} in your account. Woohoo! it was sent by {{Sender}} on Dec 24,2024 -{{Bank}}"
  