- name: Ansible Datatypes
  hosts: local
  connection: local
  vars:
    Series: India tour of Australia #string
    Match: 4 #num
    Venue: Melbourne
    Batsmen: # lists
      -KL Rahul
      - Jaiswal
      - Gill
      - Virat
      - Pant
      - Rohit
    Support Staff: #map/dictionary
      Head-Coach: Gambhir
      Fielding: Arun
      Batting: Abhishek
      Bowling: Mornie
    Rain: false #boolean
  tasks:
    - name: Datatypes
      ansible.builtin.debug:
        msg: "Welcome to {{Series}}- Test{{Match}} @{{Venue}} India Squad:{{Batsmen}} Support Staff:{{Support staff}} Weather condition{{Rain}}"