- name: When Condition
  hosts: local
  connection: local
  vars_prompt:
  - name: num
    prompt: Enter number
    private: false

  tasks:
  - name: print if grea than 10
    ansible.builtin.debug:
      msg: "{{ num }} is greather than 10"
    when: num | int > 10  

  - name: print if less than 10
    ansible.builtin.debug:
      msg: "{{ num }} is less than 10"
    when: num | int < 10
  
