- name: Install nginx
  hosts: web
  become: yes
  tasks:
    - name: Print Facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
    
    - name: Install nginx for redhat
      ansible.builtin.dnf:
        name: nginx
        state: started
      when: ansible_os_family == "RedHat"

    - name: Install nginx for Debian
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"