- name: Shell Vs Command
  hosts: local
  connection: local

  tasks:
  - name: create file and append logs
    ansible.builtin.shell: ls -ltr > /tmp/output.txt #logins into server and executes cmnd

  - name: check process
    ansible.builtin.shell: ps -ef | grep ssh
    register: output

  - name: check process with command mod
    ansible.builtin.command: ps -ef | grep ssh
    register: ourput
