- name: Create EC2 and R53
  hosts: local
  connection: local
  vars:
    sg_id: "sg-0544fbda6915c7068"
    ami_id: "ami-09c813fb71547fc4f"
    subnet_id: "subnet-04c1d9e4a6a0a6393"
    instances:
    - mysql
    - backend
    - frontend
    zone: charanworld.online
  tasks:
  - name:
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      image_id: "{{ ami_id }}"
      instance_type: "t3.micro"
      vpc_subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  
  - name: print ec2_details
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
  
  - name: create R53 Private records
    amazon.aws.rote53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create public R53 record for frontend
    amazon.aws.rote53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip}}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"